services:
  mysql:
    image: mysql:${MYSQL_VERSION?}
    environment:
      - MYSQL_ROOT_PASSWORD=honored
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql-${MYSQL_VERSION?}:/var/lib/mysql
  postgres:
    image: postgres:${POSTGRES_VERSION?}
    environment:
      POSTGRES_USER: honored
      POSTGRES_PASSWORD: honored
      POSTGRES_DB: honored
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-${POSTGRES_VERSION?}/:/var/lib/postgresql/data/
  redis:
    image: redis:${REDIS_VERSION?}
    ports:
      - 6379:6379
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/opensearch-data1:/usr/share/opensearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
